name: ExBrainable
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
- mkl
- matplotlib
- numpy
- pip
- python>=3.7 
#- h5py
- pytorch
#- pytest
- scipy
- tk
- pip:
  - mne 
  - torchsummary
  - sklearn
  #- https://github.com/CECNL/ExBrainable.git
  

